<?php
return [
    [
        "user_id" => 1,
        "name" => "Meredith Grey",
        "description" => "she is the queen",
        "address" => "via mazzini 9",
        "photo" => "doctorsImg/d1.jpeg",
        "visibility" => true,
    ],
    // [
    //     "user_id" => 2,
    //     "name" => "Gianluca Esposito",
    //     "description" => "Competente e premuroso",
    //     "address" => "via garibaldi 30",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
    // [
    //     "user_id" => 3,
    //     "name" => "Roberto Ferretti",
    //     "description" => "Preciso e diretto",
    //     "address" => "via matteotti 12",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
    // [
    //     "user_id" => 4,
    //     "name" => "Francesco Lubrano",
    //     "description" => "Da sempre amante di questa professione",
    //     "address" => "via sonnino 21",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
    // [
    //     "user_id" => 5,
    //     "name" => "Giuseppe Trovato",
    //     "description" => "Chirurgo di fama internazionale",
    //     "address" => "via napoleone 5",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
    // [
    //     "user_id" => 6,
    //     "name" => "Piergiorgio Antonelli",
    //     "description" => "Volenteroso di dimostrare le sue capacità",
    //     "address" => "via delle province 7",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
    // [
    //     "user_id" => 7,
    //     "name" => "Martina Bianchi",
    //     "description" => "Ritiene il lato umano fondamentale per questa professione",
    //     "address" => "via pitagora 55",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
    // [
    //     "user_id" => 8,
    //     "name" => "Frederik Van Goorst",
    //     "description" => "Esperienza pluriennale nel suo campo",
    //     "address" => "via dell' università 3",
    //     "photo" => "",
    //     "visibility" => true,
    // ],
];